build_mode = "release"
target_adapters = [
    "circom",
    "halo2",
]
target_platforms = ["android"]
ios = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-ios",
]
android = ["aarch64-linux-android"]
